import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/public/css/bootstrap.min.css";
import "@/public/css/landing-style.css";
import "@/public/css/owl.carousel.min.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Script type="text/javascript" src="/js/jquery-3.3.1.min.js"></Script>
        <Script type="text/javascript" src="/js/bootstrap.bundle.min.js"></Script>
        <Script type="text/javascript" src="/js/owl.carousel.min.js"></Script>
      </body>
    </html>
  );
}
